# Пользователи
## Создать нового пользователя

POST http://localhost:27018/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "kotelnikova@tinkoff.com",
  "avatar": "kot.png",
  "name": "Kseniya Kotelnikova",
  "password": "koshka",
  "userType": "pro"
}

###

## Авторизовать пользователя

POST http://localhost:27018/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "kotelnikova@tinkoff.com",
  "password": "koshka"
}

###

## Проверить токен пользователя

GET http://localhost:27018/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImtvdGVsbmlrb3ZhQHRpbmtvZmYuY29tIiwiaWQiOiI2NzVlMDJiODA3ZjdhMzJkMTIxZWIyNzEiLCJpYXQiOjE3MzQyMTQ0NDAsImV4cCI6MTczNDM4NzI0MH0.RjM4qHE43kuLsbfdvBv0Af6_1dg0JrqvEvZumhxPQGM

###
